// Prueba real y aislada; no usa ni modifica la DATABASE_URL del usuario.
import {spawn,spawnSync} from 'node:child_process';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve,dirname} from 'node:path';
import assert from 'node:assert/strict';
import {portableDump} from '../server/restore-sql.js';
import {parseExercises} from '../server/exercises.js';
const folder=await mkdtemp(join(tmpdir(),'aula-integration-'));
const bin=process.env.PG_BIN||'C:/pgsql/bin';
const run=(name,args,env={})=>{const r=spawnSync(join(bin,name),args,{windowsHide:true,encoding:'utf8',stdio:name==='pg_ctl'?'ignore':'pipe',env:{...process.env,...env}});if(r.error||r.status!==0)throw new Error(r.error?.message||r.stderr||r.stdout||`${name} falló`);return r.stdout};
let server,started=false;
try{
 run('initdb',['-D',join(folder,'db'),'-A','trust','-U','aula_test','--encoding=UTF8','--locale=C']);
 run('pg_ctl',['-D',join(folder,'db'),'-l',join(folder,'postgres.log'),'-o','-h 127.0.0.1 -p 55439','-w','start']);started=true;
 const sql=portableDump(await readFile('preplytool_backup.dump','utf8'));
 await writeFile(join(folder,'restore.sql'),sql);
 run('psql',['-h','127.0.0.1','-p','55439','-U','aula_test','-d','postgres','-v','ON_ERROR_STOP=1','--single-transaction','-f',join(folder,'restore.sql')]);
 run('psql',['-h','127.0.0.1','-p','55439','-U','aula_test','-d','postgres','-v','ON_ERROR_STOP=1','-f',resolve('server/migration.sql')]);
 server=spawn(process.execPath,['server/index.js'],{windowsHide:true,stdio:['ignore','pipe','pipe'],env:{...process.env,PORT:'3009',DATABASE_URL:'postgresql://aula_test@127.0.0.1:55439/postgres',DATABASE_SSL:'false',JWT_SECRET:'integration-secret-with-more-than-32-characters',TEACHER_EMAIL:'teacher@test.local',TEACHER_PASSWORD:'integration-password'}});
 await new Promise((ok,fail)=>{const timer=setTimeout(()=>fail(new Error('API no inició')),10000);server.stdout.once('data',()=>{clearTimeout(timer);ok()});server.once('exit',()=>{clearTimeout(timer);fail(new Error('API terminó antes de iniciar'))})});
 const call=async(path,{token,method='GET',body,status=200}={})=>{const r=await fetch('http://127.0.0.1:3009/api'+path,{method,headers:{'Content-Type':'application/json',Authorization:'Bearer '+(token||'')},body:body?JSON.stringify(body):undefined});const value=await r.json();assert.equal(r.status,status,JSON.stringify(value));return value};
 await call('/catalog',{status:401});
 const teacher=(await call('/login',{method:'POST',body:{email:'teacher@test.local',password:'integration-password'}})).token;
 const catalog=await call('/catalog',{token:teacher});assert.equal(catalog.lecciones.length,163);
 const a=await call('/students',{token:teacher,method:'POST',body:{nombre:'Prueba aislada'}});
 const b=await call('/students',{token:teacher,method:'POST',body:{nombre:'Otro alumno'}});
 const l=await call('/lessons',{token:teacher,method:'POST',body:{nombre:'Clase de prueba',etapa_id:catalog.etapas[0].id,contenido_leccion:'<p style="color:#112233">Hola</p><script>alert(1)</script>',ejercicios_leccion:JSON.stringify([{id:'uno',type:'fill',question:'Saludo',answer:'Hola'}])}});
 assert.ok(!l.contenido_leccion.includes('script'));
 await call(`/students/${a.id}/progress/${l.id}`,{token:teacher,method:'PUT',body:{completed:true,notes:'Nota persistida'}});
 const access=await call(`/students/${a.id}/access`,{token:teacher,method:'POST'});
 const student=(await call('/login',{method:'POST',body:{token:access.token}})).token;
 const progress=await call(`/students/${a.id}/progress`,{token:student});assert.equal(progress[0].notes,'Nota persistida');assert.equal(progress[0].completed,true);
 await call(`/students/${b.id}/progress`,{token:student,status:403});
 await call(`/students/${a.id}/progress/${l.id}`,{token:student,method:'PUT',body:{completed:false,notes:'No autorizado'},status:403});
 await call('/lessons',{token:student,method:'POST',body:{},status:403});
 const ownCatalog=await call('/catalog',{token:student});assert.equal(JSON.parse(ownCatalog.lecciones.find(x=>x.id===l.id).ejercicios_leccion)[0].answer,undefined);
 const original=catalog.lecciones.find(x=>x.id===36);
 const originalPublic=ownCatalog.lecciones.find(x=>x.id===36);
 assert.equal(originalPublic.exercise_document.kind,'legacy');assert.equal(originalPublic.ejercicios_leccion,null);
 assert.ok(originalPublic.exercise_document.html.includes('data-gap-id'));
 assert.ok(!originalPublic.exercise_document.html.includes('{peine}'));
 const originalAnswers=Object.fromEntries(parseExercises(original.ejercicios_leccion).map(e=>[e.id,e.answer]));
 const originalResult=await call('/lessons/36/check',{token:teacher,method:'POST',body:{answers:originalAnswers}});assert.equal(originalResult.score,100);
 await call(`/students/${a.id}/submissions/36`,{token:student,method:'POST',body:{answers:originalAnswers}});
 const originalSubmission=await call(`/students/${a.id}/submissions/36`,{token:student});assert.equal(originalSubmission.result.score,100);
 const draft=await call('/exercises/preview',{token:teacher,method:'POST',body:{html:'<p>Mi hermano {él}</p>'}});assert.ok(draft.html.includes('data-gap-id'));assert.ok(!draft.html.includes('{él}'));
 const draftResult=await call('/exercises/check',{token:teacher,method:'POST',body:{html:'<p>Mi hermano {él}</p>',answers:{'legacy-0':'él'}}});assert.equal(draftResult.score,100);
 await call('/exercises/check',{token:student,method:'POST',body:{html:'<p>{a}</p>'},status:403});
 const saved=await call(`/lessons/${l.id}`,{token:teacher,method:'PUT',body:{...l,contenido_leccion:'<p><img src="data:image/png;base64,iVBORw0KGgo=" width="373" height="187" style="width:373px"/></p>',ejercicios_leccion:'<p>Escribe {hola}</p>'}});
 assert.ok(saved.contenido_leccion.includes('data:image/png'));assert.ok(saved.contenido_leccion.includes('width="373"'));assert.equal(saved.exercise_document.exercises.length,1);
 // Volver al ejercicio moderno para comprobar también su persistencia.
 await call(`/lessons/${l.id}`,{token:teacher,method:'PUT',body:l});
 const result=await call(`/students/${a.id}/submissions/${l.id}`,{token:student,method:'POST',body:{answers:{uno:' hola '}}});assert.equal(result.score,100);
 const submission=await call(`/students/${a.id}/submissions/${l.id}`,{token:student});assert.equal(submission.score,100);
 await call(`/students/${a.id}/access`,{token:teacher,method:'POST'});
 await call('/login',{method:'POST',body:{token:access.token},status:401});
 const level=await call('/levels',{token:teacher,method:'POST',body:{nombre:'Nivel nuevo',orden_nivel:8}});
 const stage=await call('/stages',{token:teacher,method:'POST',body:{nombre:'Etapa nueva',nivel_id:level.id,orden_etapa:2}});
 const stage2=await call('/stages',{token:teacher,method:'POST',body:{nombre:'Otra etapa',nivel_id:level.id,orden_etapa:3}});
 await call('/catalog/reorder',{token:teacher,method:'POST',body:{kind:'stages',parent_id:level.id,ids:[stage2.id,stage.id]}});
 const reordered=await call('/catalog',{token:teacher});assert.equal(reordered.etapas.find(s=>s.id===stage2.id).orden_etapa,1);assert.equal(reordered.etapas.find(s=>s.id===stage.id).orden_etapa,2);
 await call('/catalog/reorder',{token:teacher,method:'POST',body:{kind:'stages',parent_id:level.id,ids:[stage.id]},status:409});
 await call('/catalog/reorder',{token:teacher,method:'POST',body:{kind:'stages',parent_id:level.id,ids:[stage.id,stage.id]},status:400});
 await call('/catalog/reorder',{token:student,method:'POST',body:{kind:'stages',parent_id:level.id,ids:[stage.id,stage2.id]},status:403});
 await call(`/stages/${stage2.id}`,{token:teacher,method:'DELETE'});
 await call(`/levels/${level.id}`,{token:teacher,method:'DELETE',status:409});
 await call(`/levels/${level.id}`,{token:teacher,method:'PUT',body:{...level,nombre:'Nivel editado'}});
 await call(`/lessons/${l.id}/location`,{token:teacher,method:'PATCH',body:{etapa_id:stage.id,orden_leccion:5}});
 await call(`/stages/${stage.id}`,{token:teacher,method:'DELETE',status:409});
 await call(`/stages/${stage.id}`,{token:teacher,method:'PUT',body:{...stage,nivel_id:catalog.niveles[0].id,nombre:'Etapa movida'}});
 const moved=await call('/catalog',{token:teacher});assert.equal(moved.lecciones.find(x=>x.id===l.id).etapa_id,stage.id);assert.equal(moved.etapas.find(x=>x.id===stage.id).nivel_id,catalog.niveles[0].id);
 assert.equal((await call(`/students/${a.id}/progress`,{token:student})).find(p=>p.lesson_id===l.id).notes,'Nota persistida');
 assert.equal((await call(`/students/${a.id}/submissions/${l.id}`,{token:student})).score,100);
 await call(`/lessons/${l.id}/location`,{token:teacher,method:'PATCH',body:{etapa_id:999999},status:400});
 await call(`/lessons/${l.id}`,{token:student,method:'DELETE',status:403});
 await call('/levels',{token:student,method:'POST',body:{nombre:'No'},status:403});
 await call(`/lessons/${l.id}`,{token:teacher,method:'DELETE'});
 assert.ok(!(await call(`/students/${a.id}/progress`,{token:student})).some(p=>p.lesson_id===l.id));
 assert.equal(await call(`/students/${a.id}/submissions/${l.id}`,{token:student}),null);
 await call(`/stages/${stage.id}`,{token:teacher,method:'DELETE'});
 await call(`/levels/${level.id}`,{token:teacher,method:'DELETE'});
 console.log('Integración OK: PostgreSQL, ejercicios, progreso, organización, movimientos, borrados y permisos.');
}finally{
 if(server){server.kill();await new Promise(ok=>server.exitCode!==null?ok():server.once('exit',ok))}
 if(started)run('pg_ctl',['-D',join(folder,'db'),'-m','fast','-w','stop']);
 const absolute=resolve(folder);if(dirname(absolute)===resolve(tmpdir())&&absolute.split(/[\\/]/).pop().startsWith('aula-integration-'))await rm(absolute,{recursive:true,force:true});
}
