import React,{useEffect,useState,lazy,Suspense} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,GraduationCap,LayoutDashboard,NotebookPen,Plus,Search,ArrowUpRight,LogOut,Check,ChevronRight,Sparkles} from 'lucide-react';
const Editor=lazy(()=>import('./Editor.jsx').then(module=>({default:module.Editor})));
import './styles.css';
import './editor.css';
import {api} from './api.js';
import {Lesson} from './Lesson.jsx';
import {StudentAvatar} from './StudentAvatar.jsx';
import {CatalogManager} from './CatalogManager.jsx';
import {LibraryBrowser,initialLibraryView} from './LibraryBrowser.jsx';
import './lesson-features.css';
import {ThemeToggle} from './ThemeToggle.jsx';
import {CoverImage} from './CoverImage.jsx';
import {appendVocabulary} from './vocabulary.js';
import './theme.css';
const sorted=(items,key)=>[...items].sort((a,b)=>(a[key]??0)-(b[key]??0));
function App(){
 const [config,setConfig]=useState(null),[user,setUser]=useState(()=>JSON.parse(sessionStorage.getItem('user')||'null')),[data,setData]=useState(null),[students,setStudents]=useState([]),[page,setPage]=useState('dashboard'),[lesson,setLesson]=useState(null),[editing,setEditing]=useState(false),[student,setStudent]=useState(null),[progress,setProgress]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[access,setAccess]=useState('');
 const teacher=user?.role==='teacher',preview=config?.preview;
 const [progressLoading,setProgressLoading]=useState(false);
 const [libraryView,setLibraryView]=useState(initialLibraryView),[libraryPath,setLibraryPath]=useState({level:null,stage:null});
 const [studentSearch,setStudentSearch]=useState('');
 const normalizeName=value=>(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim();
 const filteredStudents=students.filter(s=>normalizeName(s.nombre).includes(normalizeName(studentSearch)));
 async function load(){try{const [d,s]=await Promise.all([api('/catalog'),api('/students')]);setData(d);setStudents(s);if(user?.role==='student')setStudent(s[0]);else setStudent(current=>s.find(value=>value.id===current?.id)||null)}catch(e){setError(e.message)}}
 useEffect(()=>{api('/config').then(setConfig).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(config&&(config.preview||user))load()},[config,user]);
 useEffect(()=>{let active=true;setAccess('');setProgress([]);setProgressLoading(Boolean(student));if(student){api(`/students/${student.id}/progress`).then(value=>{if(active)setProgress(value)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setProgressLoading(false)})}return()=>{active=false}},[student?.id]);
 function selectStudent(id){const selected=students.find(s=>s.id===id)||null;if(selected)setStudentSearch('');if(selected?.id!==student?.id){setProgress([]);setAccess('');setStudent(selected)}}
 async function saveProgress(value){if(!student)throw new Error('Selecciona un alumno.');setBusy(true);try{const saved=await api(`/students/${student.id}/progress/${lesson.id}`,{method:'PUT',body:value});setProgress(old=>[...old.filter(p=>p.lesson_id!==lesson.id),saved]);return saved}finally{setBusy(false)}}
 async function action(fn){setBusy(true);setError('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
 function logout(){sessionStorage.clear();setUser(null);setData(null);setStudent(null);setLesson(null)}
 const completed=progress.filter(p=>p.completed).length;
 function navigate(id){setPage(id);setLesson(null);setEditing(false);if(user?.role!=='student'&&!['students','notes'].includes(id))selectStudent(0)}
 function editLesson(){if(user?.role!=='student')selectStudent(0);setPage('lessons');setEditing(true)}
 function createLesson(stage=''){if(user?.role!=='student')selectStudent(0);setPage('lessons');setLesson({nombre:'',etapa_id:stage,contenido_leccion:'',ejercicios_leccion:'[]'});setEditing(true)}
 const open=l=>{setLesson(l);setEditing(false)};
 if(!config)return <div className="loading">{error||'Preparando tu aula…'}</div>;
 if(!preview&&!user)return <Login onLogin={setUser} error={error} config={config}/>;
 return <div className="shell"><aside><a className="brand" href="/"><span className="brand-icon"><img className="brand-logo" src="/brand/preplytool-v2-logo.png" alt=""/></span><span className="brand-name">preplytool <span className="brand-version">v2</span></span></a><div className="workspace">TU ESPACIO DE ENSEÑANZA</div><nav>{[['dashboard',LayoutDashboard,'Vista general'],['lessons',BookOpen,'Biblioteca de clases'],['students',GraduationCap,teacher||preview?'Mis alumnos':'Mi progreso'],['notes',NotebookPen,'Notas de clase']].map(([id,Icon,label])=><button key={id} className={page===id?'active':''} onClick={()=>navigate(id)}><Icon size={19}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="help-card"><Sparkles size={21}/><strong>Un espacio para aprender</strong><p>Cada clase, un paso más.</p></div><div className="profile"><StudentAvatar student={user?.role==='student'?student:{nombre:'Profesor'}}/><div><strong>{user?.role==='student'?student?.nombre||'Alumno':'Profesor'}</strong><small>{preview?'Vista del respaldo':'Tu espacio de enseñanza'}</small></div>{!preview&&<button aria-label="Cerrar sesión" onClick={logout}><LogOut size={17}/></button>}</div></div></aside><main><header><span>Mi espacio <ChevronRight size={14}/> {lesson?'Clase':{dashboard:'Vista general',lessons:'Biblioteca',students:'Alumnos',notes:'Notas'}[page]}</span><div className="header-right"><span className="status-dot"/>{preview?'Respaldo conectado':'PostgreSQL conectado'}</div></header><div className="main-content">{preview&&<div className="preview-banner">Vista de lectura con los datos reales de tu respaldo. Completa .env, restaura PostgreSQL y ejecuta la migración para habilitar edición y portales.</div>}{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')}>×</button></div>}{!data?<div className="loading">{error?'No se pudo cargar el aula.':'Cargando tus clases…'}</div>:<>
 {lesson?(editing?<Editor lesson={lesson} stages={data.etapas} levels={data.niveles} disabled={busy} onCancel={()=>setEditing(false)} onSave={b=>action(async()=>{const saved=await api(lesson.id?`/lessons/${lesson.id}`:'/lessons',{method:lesson.id?'PUT':'POST',body:b});await load();setLesson(saved);setEditing(false)})}/>:<Lesson lesson={lesson} student={student} teacher={teacher} preview={preview} progress={progress} busy={busy} onBack={()=>setLesson(null)} onEdit={editLesson} onVocabulary={async(word,definition,source)=>{setBusy(true);try{const saved=await api(`/lessons/${lesson.id}`,{method:'PUT',body:{...lesson,contenido_leccion:appendVocabulary(lesson.contenido_leccion,word,definition,source)}});setLesson(saved);await load()}finally{setBusy(false)}}} progressLoading={progressLoading} onProgress={saveProgress}/>):<>
 <div className="page-title"><div><div className="eyebrow">{page==='dashboard'?'TU AULA, EN UN SOLO LUGAR':'APRENDER CON INTENCIÓN'}</div><h1>{{dashboard:user?.role==='student'?`Hola, ${student?.nombre||'estudiante'}`:'Cada clase cuenta.',lessons:'Biblioteca de clases',students:teacher||preview?'Conoce su avance.':'Mi progreso',notes:'Lo que aprendimos.'}[page]}</h1><p>{{dashboard:'Organiza tus clases y acompaña el camino de cada alumno.',lessons:'Lecciones compartidas para todos tus alumnos. Crea y edita aquí el material de la biblioteca.',students:'Un recorrido individual, una clase a la vez.',notes:'Recupera las notas y los momentos importantes de clases anteriores.'}[page]}</p></div>{teacher&&page==='lessons'&&<button className="primary" onClick={()=>createLesson(libraryView==='sections'?libraryPath.stage||'':'')}><Plus size={17}/>Nueva lección</button>}</div>
 {page==='dashboard'&&<><div className="stats">{[[BookOpen,data.lecciones.length,'Clases en tu biblioteca','Material listo para enseñar'],[GraduationCap,students.length,'Alumnos','Cada uno con su propio camino'],[NotebookPen,data.niveles.length,'Niveles de aprendizaje','De los primeros pasos a la fluidez']].map(([Icon,count,label,small])=><div className="stat" key={label}><div className="stat-top"><span>{label}</span><Icon size={19}/></div><strong>{count}</strong><small>{small}</small></div>)}</div><div className="feature"><div><span className="tag">ENSEÑAR · CONECTAR · CRECER</span><h2>El próximo gran paso<br/>empieza en tu próxima clase.</h2><p>Todo tu material y el progreso de tus alumnos,<br/>en un espacio pensado para ti.</p><button onClick={()=>navigate('lessons')}>Explorar biblioteca <ArrowUpRight size={16}/></button></div><div className="feature-art"><div className="art-circle"/><div className="paper"><span>ESPAÑOL</span><h3>Hola,<br/>¿qué tal?</h3><div className="paper-lines"/><div className="paper-stamp">Aa</div></div><div className="mini-note"><Check size={20}/> Un paso más.</div></div></div><div className="section-title"><h2>De tu biblioteca</h2><button onClick={()=>navigate('lessons')}>Ver todas <ArrowUpRight size={16}/></button></div><LessonCards lessons={sorted(data.lecciones,'orden_leccion').slice(0,6)} data={data} open={open} progress={progress}/></>}
 {page==='lessons'&&<><LibraryBrowser data={data} view={libraryView} onViewChange={setLibraryView} path={libraryPath} onPathChange={setLibraryPath} renderLessons={lessons=><LessonCards lessons={lessons} data={data} open={open} progress={progress}/>}/>{teacher&&<details className="library-management"><summary>Organizar biblioteca</summary><CatalogManager data={data} teacher={teacher} onRefresh={load} onOpen={(l,edit=false)=>{selectStudent(0);setLesson(l);setEditing(edit)}} onCreate={createLesson}/></details>}</>}
 {(page==='students'||page==='notes')&&<><div className="filters">{(teacher||preview)&&<label className="search"><Search size={18}/><input type="search" aria-label="Buscar alumnos" placeholder="Buscar alumno por nombre…" value={studentSearch} onChange={e=>{setStudentSearch(e.target.value);selectStudent(0)}}/></label>}<label>Alumno <select value={student?.id||''} onChange={e=>selectStudent(Number(e.target.value))}><option value="">Selecciona un alumno</option>{filteredStudents.map(s=><option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label>{teacher&&page==='students'&&<button onClick={()=>action(async()=>{const nombre=prompt('Nombre del nuevo alumno');if(nombre?.trim()){await api('/students',{method:'POST',body:{nombre}});await load()}})}><Plus size={16}/>Nuevo alumno</button>}</div>{student?<><div className="student-summary"><StudentAvatar student={student} large/><div><h2>{student.nombre}</h2><p>{completed} de {data.lecciones.length} clases completadas</p><div className="progress-track"><span style={{width:`${data.lecciones.length?completed/data.lecciones.length*100:0}%`}}/></div></div>{teacher&&<button disabled={busy} onClick={()=>action(async()=>{const r=await api(`/students/${student.id}/access`,{method:'POST'});setAccess(`${location.origin}/?access=${r.token}`)})}>Crear enlace de acceso</button>}</div>{access&&<div className="access-box"><strong>Enlace privado del alumno (el acceso anterior queda reemplazado)</strong><input readOnly value={access} onFocus={e=>e.target.select()}/><button onClick={()=>action(()=>navigator.clipboard.writeText(access))}>Copiar enlace</button></div>}{page==='notes'?<div className="notes-list">{progress.filter(p=>p.notes).length?progress.filter(p=>p.notes).map(p=><article key={p.id}><span className="tag">{p.completed?'CLASE COMPLETADA':'EN PROGRESO'}</span><h3>{data.lecciones.find(l=>l.id===p.lesson_id)?.nombre}</h3><small>{p.updated_at&&new Date(p.updated_at).toLocaleDateString('es-MX')}</small><p className="note-text">{p.notes}</p><button onClick={()=>open(data.lecciones.find(l=>l.id===p.lesson_id))}>Abrir clase <ArrowUpRight size={16}/></button></article>):<div className="empty">Todavía no hay notas de clases para este alumno.</div>}</div>:<LessonCards lessons={sorted(data.lecciones,'orden_leccion')} data={data} open={open} progress={progress}/>}</>:<div className="student-grid">{filteredStudents.map(s=><button className="student-card" key={s.id} onClick={()=>selectStudent(s.id)}><StudentAvatar student={s}/><strong>{s.nombre}</strong><ChevronRight size={17}/></button>)}{!filteredStudents.length&&<div className="empty">{studentSearch.trim()?'No hay alumnos que coincidan con tu búsqueda.':'Todavía no hay alumnos.'}</div>}</div>}</>}
 </>}
 </>}</div><footer>preplytool v2 <span>Hecho para enseñar con calma.</span></footer></main></div>
}
function LessonCards({lessons,data,open,progress}){return <div className="lesson-grid">{lessons.map((l,i)=>{const stage=data.etapas.find(e=>e.id===l.etapa_id),level=data.niveles.find(n=>n.id===stage?.nivel_id);return <button className="lesson-card" key={l.id} onClick={()=>open(l)}><div className={'card-cover theme-'+i%4}><CoverImage source={l.img_banner} compact/><span className="cover-level">{level?.nombre||'ESPAÑOL'}</span><span className="cover-symbol">{['Aa','¿?','Ñ','¡!'][i%4]}</span>{progress.find(p=>p.lesson_id===l.id)?.completed&&<span className="completed"><Check size={15}/>Completada</span>}</div><div className="card-body"><small>{stage?.nombre}</small><h3>{l.nombre||l.titulo_clase}</h3><div><span>Ver clase</span><ArrowUpRight size={18}/></div></div></button>})}{!lessons.length&&<div className="empty">No hay clases que coincidan con tu búsqueda.</div>}</div>}
function Login({onLogin,config}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{const token=new URLSearchParams(location.search).get('access');if(token)login({token})},[]);async function login(body){setBusy(true);try{const r=await api('/login',{method:'POST',body});sessionStorage.setItem('session',r.token);sessionStorage.setItem('user',JSON.stringify(r.user));history.replaceState(null,'',location.pathname);onLogin(r.user)}catch(e){setError(e.message)}finally{setBusy(false)}}return <div className="login"><div className="login-card"><div className="brand"><span className="brand-icon"><img className="brand-logo" src="/brand/preplytool-v2-logo.png" alt=""/></span><span className="brand-name">preplytool <span className="brand-version">v2</span></span></div><h1>Tu próxima clase<br/>empieza aquí.</h1><p>Entra a tu espacio de enseñanza.</p>{!config.authReady&&<div className="preview-banner">Completa las credenciales y JWT_SECRET en .env.</div>}<form onSubmit={e=>{e.preventDefault();login({email,password})}}><label>Correo del profesor<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>Entrar al aula</button></form><small>Alumnos: utiliza el enlace privado que te comparte tu profesor.</small></div></div>}
createRoot(document.getElementById('root')).render(<Suspense fallback={<div className="loading">Cargando editor…</div>}><ThemeToggle/><App/></Suspense>);
















